	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 1)
	{//спавн на 1 дм
		new rand = random(sizeof(DM1SPAWN));
		x = DM1SPAWN[rand][0]; y = DM1SPAWN[rand][1]; z = DM1SPAWN[rand][2]; Angle = DM1SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 1 дм
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 2)
	{//спавн на 2 дм
		new rand = random(sizeof(DM2SPAWN));
		x = DM2SPAWN[rand][0]; y = DM2SPAWN[rand][1]; z = DM2SPAWN[rand][2]; Angle = DM2SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 2 дм
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 3)
	{//спавн на 3 дм
		new rand = random(sizeof(GG3SPAWN));
		x = GG3SPAWN[rand][0]; y = GG3SPAWN[rand][1]; z = GG3SPAWN[rand][2]; Angle = GG3SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 3 дм
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 4)
	{//спавн на 4 дм
		new rand = random(sizeof(DM4SPAWN));
		x = DM4SPAWN[rand][0]; y = DM4SPAWN[rand][1]; z = DM4SPAWN[rand][2]; Angle = DM4SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 4 дм
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 5)
	{//спавн на 5 дм
		new rand = random(sizeof(DM5SPAWN));
		x = DM5SPAWN[rand][0]; y = DM5SPAWN[rand][1]; z = DM5SPAWN[rand][2]; Angle = DM5SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 5 дм
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 6)
	{//спавн на 6 дм
		new rand = random(sizeof(DM6SPAWN));
		x = DM6SPAWN[rand][0]; y = DM6SPAWN[rand][1]; z = DM6SPAWN[rand][2]; Angle = DM6SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 6 дм
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 7)
	{//спавн на 7 дм
		new rand = random(sizeof(GG7SPAWN));
		x = GG7SPAWN[rand][0]; y = GG7SPAWN[rand][1]; z = GG7SPAWN[rand][2]; Angle = GG7SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 7 дм
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 8)
	{//спавн на 8 дм
		new rand = random(sizeof(DM8SPAWN));
		x = DM8SPAWN[rand][0]; y = DM8SPAWN[rand][1]; z = DM8SPAWN[rand][2]; Angle = DM8SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 8 дм
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 9)
	{//спавн на 9 дм
		new rand = random(sizeof(DM9SPAWN));
		x = DM9SPAWN[rand][0]; y = DM9SPAWN[rand][1]; z = DM9SPAWN[rand][2]; Angle = DM9SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 9 дм
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 10)
	{//спавн на 10 дм
		new rand = random(sizeof(DM10SPAWN));
		x = DM10SPAWN[rand][0]; y = DM10SPAWN[rand][1]; z = DM10SPAWN[rand][2]; Angle = DM10SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 10 дм
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 11)
	{//спавн на 11 гг
		new rand = random(sizeof(DM11SPAWN));
		x = DM11SPAWN[rand][0]; y = DM11SPAWN[rand][1]; z = DM11SPAWN[rand][2]; Angle = DM11SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 11 гг
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 12)
	{//спавн на 12 гг
		new rand = random(sizeof(DM12SPAWN));
		x = DM12SPAWN[rand][0]; y = DM12SPAWN[rand][1]; z = DM12SPAWN[rand][2]; Angle = DM12SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 12 гг
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 13)
	{//спавн на 13 гг
		new rand = random(sizeof(DM13SPAWN));
		x = DM13SPAWN[rand][0]; y = DM13SPAWN[rand][1]; z = DM13SPAWN[rand][2]; Angle = DM13SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 13 гг
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 14)
	{//спавн на 14 гг
		new rand = random(sizeof(DM7SPAWN));
		x = DM7SPAWN[rand][0]; y = DM7SPAWN[rand][1]; z = DM7SPAWN[rand][2]; Angle = DM7SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 14 гг
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 15)
	{//спавн на 15 гг
		new rand = random(sizeof(DM15SPAWN));
		x = DM15SPAWN[rand][0]; y = DM15SPAWN[rand][1]; z = DM15SPAWN[rand][2]; Angle = DM15SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 15 гг
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 16)
	{//спавн на 16 гг
		new rand = random(sizeof(DM16SPAWN));
		x = DM16SPAWN[rand][0]; y = DM16SPAWN[rand][1]; z = DM16SPAWN[rand][2]; Angle = DM16SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 16 гг
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 17)
	{//спавн на 17 гг
		new rand = random(sizeof(DM17SPAWN));
		x = DM17SPAWN[rand][0]; y = DM17SPAWN[rand][1]; z = DM17SPAWN[rand][2]; Angle = DM17SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);SetPlayerInterior(playerid, 10);
	}//спавн на 17 гг
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 18)
	{//спавн на 18 гг
		new rand = random(sizeof(DM18SPAWN));
		x = DM18SPAWN[rand][0]; y = DM18SPAWN[rand][1]; z = DM18SPAWN[rand][2]; Angle = DM18SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 18 гг
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 19)
	{//спавн на 19 гг
		new rand = random(sizeof(DM19SPAWN));
		x = DM19SPAWN[rand][0]; y = DM19SPAWN[rand][1]; z = DM19SPAWN[rand][2]; Angle = DM19SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);
	}//спавн на 19 гг
	if (JoinEvent[playerid] == EVENT_GUNGAME && GGTimeToEnd > 0 && GGid == 20)
	{//спавн на 20 гг
		new rand = random(sizeof(DM20SPAWN));
		x = DM20SPAWN[rand][0]; y = DM20SPAWN[rand][1]; z = DM20SPAWN[rand][2]; Angle = DM20SPAWN[rand][3];
		SetPlayerVirtualWorld(playerid, 701);SetPlayerInterior(playerid, 3);
	}//спавн на 20 гг
	
	//---- Оружие при спавне на гангейме
	if (GGKills[playerid] < 1) w1 = 24;
	if (GGKills[playerid] == 1) w1 = 25;
	if (GGKills[playerid] == 2) w1 = 26;
	if (GGKills[playerid] == 3) w1 = 27;
	if (GGKills[playerid] == 4) w1 = 29;
	if (GGKills[playerid] == 5) w1 = 28;
	if (GGKills[playerid] == 6) w1 = 32;
	if (GGKills[playerid] == 7) w1 = 31;
	if (GGKills[playerid] == 8) w1 = 30;
	if (GGKills[playerid] == 9) w1 = 16;
	if (GGKills[playerid] == 10) w1 = 34;
	if (GGKills[playerid] == 11) w1 = 35;
	if (GGKills[playerid] == 12 || GGKills[playerid] == 13) w1 = 38;
	if (GGKills[playerid] == 14) w1 = 8;	
	if (GGKills[playerid] == 14) w1ammo = 1; else w1ammo = 20000;